```{r}
hd <- read.table("heart.disease.txt", header = FALSE, sep = ",")
colnames(hd) <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "status")
```

```{r}
## 2 sex: (1 = male; 0 = female)
## 3 cp: chest pain type: 
##       Value 1: typical anging
##       Value 2: atypical angina
##       Value 3: non-anginal pain
##       Value 4: asymptomatic
## 4 trsetbps: resting blood pressure (mmHg)
## 5 chol: serum cholestoral in mg/dl
## 6 fbs: fasting blood sugar > 120 mg/dl (1 = true; 0 = false)
## 7 restecg: resting electrocardiographic results: 
##       Value 0: normal
##       Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
##       Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria
## 8 thalach: maximum heart rate achieved
## 9 exang: exercise induced angina (1 = yes; 0 = no)
##10 oldpeak: ST depression induced by exercise relative to rest
##11 slope: the slope of the peak exercise ST segment
##       Value 1: upsloping
##       Value 2: flat
##       Value 3: downsloping
##12 ca: number of major vessels (0-3) colored by flourosopy
##13 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect
##14 status: diagnosis of heart disease (angiographic disease status)
##       Value 0: < 50% diameter narrowing
##       Value 1: > 50% diameter narrowing (in any major vessel: attributes 59 through 68 are vessels)
##  The "goal" field refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4. Experiments with the Cleveland database have concentrated on simply attempting to distinguish presence (values 1,2,3,4) from absence (value 0).
```

## dealing with missing Data by mice()
```{r}
library(mice)
## turn missing value into NA
hd[hd == "?"] <- NA

md.pattern(hd)
#visualization of NA: only ca and thal have NA
library(VIM)
aggr(hd, col=c('navyblue','yellow'), numbers=TRUE, 
      labels=names(hd), cex.axis=.7, gap=3, 
      ylab=c("Missing data","Pattern"))
## impute the missing data
imputed <- mice(hd, m = 5, method = "cart", seed = 500)
##check the imputed data 
imputed$imp$ca
imputed$imp$thal
## complete dataset 
new_hd <- complete(imputed,1)
new_hd$ca <- as.numeric(as.character(new_hd$ca))
new_hd$thal <- as.numeric(as.character(new_hd$thal))
summary(new_hd)
nrow(new_hd[is.na(new_hd), ])
```

## categorical value into factor
```{r} 
new_hd$sex <- factor(new_hd$sex, labels = c("female", "male"))
new_hd$cp <- factor(new_hd$cp, labels = c("typical", "atypical", "non-anginal", "asymptomatic"))
new_hd$fbs <- factor(new_hd$fbs, labels = c("False", "True"))
new_hd$restecg <- factor(new_hd$restecg, labels = c("normal", "abnorm", "hyper"))
new_hd$exang <- factor(new_hd$exang, labels = c("no", "yes"))
new_hd$slope <- factor(new_hd$slope, labels = c("up", "flat", "down"))
new_hd$ca <- as.factor(new_hd$ca)
new_hd$thal <- factor(new_hd$thal, labels = c("norm", "fix", "rev"))
## status: "absenece" == 0, "presence" == 1-4
new_hd$status <- ifelse(new_hd$status == 0, "absence", "presence")
new_hd$status <- as.factor(new_hd$status)
```

## Data exploration
install.packages("ggplot2")

```{r}
library(ggplot2)
ggplot(new_hd, aes(x = status, fill = status)) + geom_bar()
```

## machine learning packages for R 
###caret
install.packages("doParallel")
install.packages("caret")
```{r}
# configure multicore
require(iterators)
library(doParallel)
cl <- makeCluster(detectCores())
registerDoParallel(cl)

library(caret)

# training, validation and test data
set.seed(42)
index <- createDataPartition(new_hd$status, p = 0.8, list = FALSE)
train_data <- new_hd[index, ]
test_data <- new_hd[-index, ]

library(dplyr)

rbind(data.frame(group = "train", train_data),
      data.frame(group = "test", test_data)) %>%  
  gather(x,y,age:thal) %>%  
  ggplot(aes(x = y, color = group, fill = group)) + 
    geom_density(alpha = 0.3) + 
    facet_wrap( ~ x, scales = "free", ncol = 3) 
```

```{r}
# Regression
#install caret package directly from github
#install.packages("devtools")
#devtools::install_github('topepo/caret/pkg/caret')
#caret:::nominalTrainWorkflow

set.seed(42)
model_glm <- caret::train(age ~ .,
                          data = train_data,
                          method = "glm", 
                          preProcess = c("scale","center"),
                          trControl = trainControl(method = "repeatedcv",
                                                   number = 10,
                                                   repeats = 10,
                                                   savePredictions = TRUE,
                                                   verboseIter = FALSE))
model_glm
#RMSE a measure of accuracy. smaller, better
#Rsquared more close to 1, stronger predictive power
#MAE mean absolute error smaller, better

#  RMSE      Rsquared   MAE     
#  7.644752  0.3169356  6.292507
```

install.packages("magrittr")
```{r}
# The pipe operator %>% was introduced to "decrease development time and to improve readability and maintainability of code. install package for %>%

library(magrittr)
library(ggplot2)

predictions <- predict(model_glm, test_data)
# model_glm$finalModel$linear.predictors == model_glm$finalMore$fitted.values
data.frame(residuals = resid(model_glm),
           predictors = model_glm$finalModel$linear.predictors)%>%
  ggplot(aes(x = predictors, y = residuals)) +
    geom_jitter() +
    geom_smooth(method = "lm")
```

```{r}
# y == train_data$age
data.frame(residuals = resid(model_glm),
           y = model_glm$finalModel$y) %>%
  ggplot(aes(x = y, y = residuals)) +
    geom_jitter() +
    geom_smooth(method = "lm")
```

```{r}
data.frame(actual = test_data$chol,
           predicted = predictions)%>%
  ggplot(aes(x = actual, y = predicted)) +
  geom_jitter() +
  geom_smooth(method = "lm") 
```

